export const PLACED_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACED_ORDER_ERROR = "PLACED_ORDER_ERROR";
export const PLACED_ORDER_REQUEST = "PLACED_ORDER_REQUEST";
export const PLACED_ORDER_RESET = "PLACED_ORDER_RESET";